name: Run Jupyter Notebook

on:
  workflow_call:
  push:
    branches:
      - develop
      - master
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.4

      - name: Install Jupyter Notebook
        run: |
          python -m pip install --upgrade pip
          pip install jupyter nbconvert
          pip install matplotlib seaborn pandas

      - name: Execute Jupyter Notebook
        run: |
          jupyter nbconvert --execute Sales_project.ipynb --to notebook --inplace
        working-directory: ${{ github.workspace }}